server.port=9090
spring.ai.deepseek.api-key=sk-d7865f3cd9954740be277771e18e7b5f
spring.ai.deepseek.base-url=https://api.deepseek.com
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.ai.mcp.client.streamable-http.connections.timemcp.url=http://localhost:8080
spring.ai.mcp.client.streamable-http.connections.timemcp.endpoint=/mcp
spring.ai.mcp.client.type=async