server.port=9090
spring.ai.deepseek.api-key=sk-f429667b2e4a4581bc1a3bb873ffa69f
spring.ai.deepseek.base-url=https://api.deepseek.com
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.mcp.client.streamable-http.connections.timemcp.url=http://localhost:8080
spring.ai.mcp.client.streamable-http.connections.timemcp.endpoint=/mcp
spring.ai.mcp.client.type=async